# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTY4ZTdhYjAyODhmYzVjY2ZjYWMxOGZhODM1NGRhNmZjNjE1MzU5YjMxOTU4MzBjMTU3MmYzNTE5MTMzNzU5OGY0YTM4OTMyZTY0NGMxOWIwMTIzOTgwNWI4OTMzZWQxODg3YTAyMTgyYWNiMGRlOTg1YTE5MDc2MzI3OGI0M2Y=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
