# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjVlNmU5MzZkOWZkMzVkNDJjMzQxMTZlODRiYWQxZDJiMDIwODQ3YWYwZGRmZjI3MWU2YjNhOTYzOTIyMzhhMDExNzgyZDA1MDc4NjA1MDYwYjhiOGY1ZDQxMjczMjlmYmI3Y2ZhNzllYTIxZjhjZGM3OWRjNjM1NDY5NTYyNTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
