# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDQwNGM3Y2QzOGU5N2FkZmQ3ZjRlYmIyMDc1YmRlZDM3ZTU5MmFhNTk3ZjMwOGU3ZTE0MDdjYTM1ZmM4YzhmZDBkNDcxN2FmOTMzNThkODdmZTA4NGQwODY2ZjJhOGY2NDAxOTFmOWNmY2UyYzVjMzdiYTEwODA5MWZhMjFiOTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
